### ISSUE TITLE
AttributeError: type object 'TabState' has no attribute 'STATE_PRINT_PREVIEWING'

### ISSUE THREAD

**Issue by overly-excessive** [jefferyto/gedit-control-your-tabs#17]
i get this error:

** (gedit:18265): WARNING **: 19:12:55.397: Error importing plugin 'controlyourtabs':
Traceback (most recent call last):
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gobochul/.local/share/gedit/plugins/controlyourtabs/__init__.py", line 31, in <module>
    from . import keyinfo, log, tabinfo, tabinfo_pre312
  File "/home/gobochul/.local/share/gedit/plugins/controlyourtabs/tabinfo.py", line 46, in <module>
    Gedit.TabState.STATE_PRINT_PREVIEWING: 'printer-symbolic',
AttributeError: type object 'TabState' has no attribute 'STATE_PRINT_PREVIEWING'

(gedit:18265): libpeas-WARNING **: 19:12:55.397: Error loading plugin 'controlyourtabs'

Any idea wath causing the problem? Thanks!

**Comment by jefferyto** [comment]
What version of gedit/OS are you using?

**Comment by overly-excessive** [comment]
gedit version 3.36.1 and im running Manjaro 19.0.2 with Gnome 3.36.1

**Comment by jefferyto** [comment]
Thanks - I won't have a full fix until new versions of Ubuntu/Fedora are released (later this month), but for now if you comment out [this line](https://github.com/jefferyto/gedit-control-your-tabs/blob/v0.3.2/controlyourtabs/tabinfo.py#L46) in tabinfo.py (and maybe also [this line](https://github.com/jefferyto/gedit-control-your-tabs/blob/v0.3.2/controlyourtabs/tabinfo_pre312.py#L49) in tabinfo_pre312.py) it should work (or you'll get the next error lol).

**Comment by overly-excessive** [comment]
yes it works now thank you!

**Comment by gregoiregentil** [comment]
Yes, commenting the line on BOTH tabinfo*.py files fixes the issue on Focal / Gnome 3.36

**Comment by jefferyto** [comment]
Thanks again for reporting - I've made a new release with a fix for this issue. Closing.
