### ISSUE TITLE
Error importing plugin 'controlyourtabs'

### ISSUE THREAD

**Issue by adamryczkowski** [jefferyto/gedit-control-your-tabs#19]
I've tried to use your excellent plugin in freshly installed Ubuntu 20.04 (i3wm), and got the following error on its Gedit 3.36.2:

```Error importing plugin 'controlyourtabs':
Traceback (most recent call last):
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adam/.local/share/gedit/plugins/controlyourtabs/__init__.py", line 31, in <module>
    from . import keyinfo, log, tabinfo, tabinfo_pre312
  File "/home/adam/.local/share/gedit/plugins/controlyourtabs/tabinfo.py", line 46, in <module>
    Gedit.TabState.STATE_PRINT_PREVIEWING: 'printer-symbolic',
AttributeError: type object 'TabState' has no attribute 'STATE_PRINT_PREVIEWING'
```

Is this problem fixable?

**Comment by jefferyto** [comment]
Are you using the latest version of the plugin (v0.3.3)?

**Comment by SharnamK** [comment]
I received the following error _today:_
`Error: Plugin loader "python" was not found.`

I fixed it by opening my controlyourplugin.plugin file and changing "python" to "python3"

**Comment by jefferyto** [comment]
@SharnamK

* Your error is different than the one described in this issue - you should open a new issue
* The [installation instructions](https://github.com/jefferyto/gedit-control-your-tabs#installation) are very clear which `.plugin` file you should use
* Are you using the latest version of the plugin (v0.3.3)?

**Comment by jefferyto** [comment]
Closing due to lack of response. Please open a new ticket for further installation issues.
